package net.mcreator.survivalreimagined.init;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;

import net.mcreator.survivalreimagined.SurvivalReimaginedMod;
import net.mcreator.survivalreimagined.util.RegistryEntry;

public final class SurvivalReimaginedModTabs {
	public static final RegistryEntry<CreativeModeTab> SURVIVAL_REBORN = registerTab();

	private SurvivalReimaginedModTabs() {
	}

	private static RegistryEntry<CreativeModeTab> registerTab() {
		var id = SurvivalReimaginedMod.asResource("survival_reborn");
		CreativeModeTab tab = FabricItemGroup.builder()
				.title(Component.translatable("item_group.survival_reimagined.survival_reborn"))
				.icon(() -> new ItemStack(SurvivalReimaginedModItems.HEART.get()))
				.displayItems((parameters, output) -> {
					output.accept(SurvivalReimaginedModItems.STONE_ROCK.get());
					output.accept(SurvivalReimaginedModItems.FLINT_TOOL.get());
					output.accept(SurvivalReimaginedModItems.HEMP_FIBER.get());
					output.accept(SurvivalReimaginedModItems.SMALL_COAL_CHUNK.get());
					output.accept(SurvivalReimaginedModItems.COPPER_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.COPPER_CHISEL.get());
					output.accept(SurvivalReimaginedModItems.STONE_HAMMER.get());
					output.accept(SurvivalReimaginedModItems.COPPER_CHUNK.get());
					output.accept(SurvivalReimaginedModItems.ANDESITE_ROCK.get());
					output.accept(SurvivalReimaginedModItems.GRANITE_ROCK.get());
					output.accept(SurvivalReimaginedModItems.DIORITE_ROCK.get());
					output.accept(SurvivalReimaginedModItems.DRIPSTONE_ROCK.get());
					output.accept(SurvivalReimaginedModItems.CALCITE_ROCK.get());
					output.accept(SurvivalReimaginedModItems.TUFF_ROCK.get());
					output.accept(SurvivalReimaginedModItems.MOSSY_STONE_ROCK.get());
					output.accept(SurvivalReimaginedModItems.NETHERRACK_ROCK.get());
					output.accept(SurvivalReimaginedModItems.END_STONE_ROCK.get());
					output.accept(SurvivalReimaginedModItems.BLACKSTONE_ROCK.get());
					output.accept(SurvivalReimaginedModItems.BASALT_ROCK.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_ROCK.get());
					output.accept(SurvivalReimaginedModItems.OBSIDIAN_ROCK.get());
					output.accept(SurvivalReimaginedModItems.SHALE.get());
					output.accept(SurvivalReimaginedModItems.SHALE_ROCK.get());
					output.accept(SurvivalReimaginedModItems.POLISHED_SHALE.get());
					output.accept(SurvivalReimaginedModItems.POLISHED_SHALE_BRICKS.get());
					output.accept(SurvivalReimaginedModItems.POLISHED_CHISELED_SHALE.get());
					output.accept(SurvivalReimaginedModItems.SHALE_STAIRS.get());
					output.accept(SurvivalReimaginedModItems.SHALE_SLAB.get());
					output.accept(SurvivalReimaginedModItems.SHALE_WALL.get());
					output.accept(SurvivalReimaginedModItems.POLISHED_SHALE_STAIRS.get());
					output.accept(SurvivalReimaginedModItems.POLISHED_SHALE_SLAB.get());
					output.accept(SurvivalReimaginedModItems.POLISHED_SHALE_WALL.get());
					output.accept(SurvivalReimaginedModItems.POLISHED_SHALE_BRICK_STAIRS.get());
					output.accept(SurvivalReimaginedModItems.POLISHED_SHALE_BRICK_SLAB.get());
					output.accept(SurvivalReimaginedModItems.POLOSHED_SHALE_BRICK_WALL.get());
					output.accept(SurvivalReimaginedModItems.OBSIDIAN_HANDLE.get());
					output.accept(SurvivalReimaginedModItems.SMALL_OBSIDIAN_HANDLE.get());

					output.accept(SurvivalReimaginedModItems.FORGE.get());
					output.accept(SurvivalReimaginedModItems.METAL_REFINING_TABLE.get());
					output.accept(SurvivalReimaginedModItems.MINERAL_PROCESSING_TABLE.get());
					output.accept(SurvivalReimaginedModItems.REACTOR_ROD.get());
					output.accept(SurvivalReimaginedModItems.DEPLETED_REACTOR_ROD.get());
					output.accept(SurvivalReimaginedModItems.TIN_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_TIN_ORE.get());
					output.accept(SurvivalReimaginedModItems.RAW_TIN.get());
					output.accept(SurvivalReimaginedModItems.TIN_CHUNK.get());
					output.accept(SurvivalReimaginedModItems.TIN_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_TIN.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_COPPER.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_IRON.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_GOLD.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_BRONZE.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_INGOT.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.COPPER_HANDLE.get());
					output.accept(SurvivalReimaginedModItems.SMALL_COPPER_HANDLE.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_HANDLE.get());
					output.accept(SurvivalReimaginedModItems.SMALL_BRONZE_HANDLE.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_SWORD.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_PICKAXE.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_AXE.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_SHOVEL.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_HOE.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_HAMMER.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_SAW.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_KNIFE.get());
					output.accept(SurvivalReimaginedModItems.TIN_INGOT.get());
					output.accept(SurvivalReimaginedModItems.BLOCK_OF_RAW_TIN.get());
					output.accept(SurvivalReimaginedModItems.BLOCK_OF_TIN.get());

					output.accept(SurvivalReimaginedModItems.HEMATITE_CHUNK.get());
					output.accept(SurvivalReimaginedModItems.HEMATITE_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.MAGNETITE_CHUNK.get());
					output.accept(SurvivalReimaginedModItems.MAGNETITE_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.CALAVERITE.get());
					output.accept(SurvivalReimaginedModItems.CALAVERITE_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.PYROLUSITE.get());
					output.accept(SurvivalReimaginedModItems.PYROLUSITE_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.URANOPHANE.get());
					output.accept(SurvivalReimaginedModItems.URANOPHANE_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.ILMENITE.get());
					output.accept(SurvivalReimaginedModItems.ILMENITE_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.ANTHRACITE.get());
					output.accept(SurvivalReimaginedModItems.SMALL_ANTHRACITE.get());
					output.accept(SurvivalReimaginedModItems.ANTHRACITE_BLOCK.get());
					output.accept(SurvivalReimaginedModItems.LIGINITE.get());
					output.accept(SurvivalReimaginedModItems.SMALL_LIGINITE.get());
					output.accept(SurvivalReimaginedModItems.LIGINITE_BLOCK.get());

					output.accept(SurvivalReimaginedModItems.RAW_MANGANESE.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_MANGANESE.get());
					output.accept(SurvivalReimaginedModItems.MANGANESE_INGOT.get());
					output.accept(SurvivalReimaginedModItems.BLOCK_OF_RAW_MANGANESE.get());
					output.accept(SurvivalReimaginedModItems.BLOCK_OF_MANGANESE.get());

					output.accept(SurvivalReimaginedModItems.ROUGH_STEEL.get());
					output.accept(SurvivalReimaginedModItems.STEEL_INGOT.get());
					output.accept(SurvivalReimaginedModItems.BLOCK_OF_STEEL.get());
					output.accept(SurvivalReimaginedModItems.BLOCK_OF_BRONZE.get());

					output.accept(SurvivalReimaginedModItems.SMALL_STICK.get());
					output.accept(SurvivalReimaginedModItems.WOOD_INGOT.get());
					output.accept(SurvivalReimaginedModItems.WOODEN_HAMMER.get());
					output.accept(SurvivalReimaginedModItems.WOODEN_SAW.get());
					output.accept(SurvivalReimaginedModItems.WOODEN_KNIFE.get());
					output.accept(SurvivalReimaginedModItems.INGOT_CLAY_MOLD.get());
					output.accept(SurvivalReimaginedModItems.CLAY_SWORD_BLADE_MOLD.get());
					output.accept(SurvivalReimaginedModItems.CLAY_PICKAXE_HEAD_MOLD.get());
					output.accept(SurvivalReimaginedModItems.CLAY_AXE_HEAD_MOLD.get());
					output.accept(SurvivalReimaginedModItems.CLAY_SHOVEL_HEAD_MOLD.get());
					output.accept(SurvivalReimaginedModItems.CLAY_HOE_BLADE_MOLD.get());
					output.accept(SurvivalReimaginedModItems.CLAY_HAMMER_HEAD_MOLD.get());
					output.accept(SurvivalReimaginedModItems.CLAY_SAW_BLADE_MOLD.get());
					output.accept(SurvivalReimaginedModItems.CLAY_KNIFE_MOLD.get());
					output.accept(SurvivalReimaginedModItems.INGOT_MOLD.get());
					output.accept(SurvivalReimaginedModItems.SWORD_BLADE_MOLD.get());
					output.accept(SurvivalReimaginedModItems.PICKAXE_HEAD_MOLD.get());
					output.accept(SurvivalReimaginedModItems.AXE_HEAD_MOLD.get());
					output.accept(SurvivalReimaginedModItems.SHOVEL_HEAD_MOLD.get());
					output.accept(SurvivalReimaginedModItems.HOE_HEAD_MOLD.get());
					output.accept(SurvivalReimaginedModItems.HAMMER_HEAD_MOLD.get());
					output.accept(SurvivalReimaginedModItems.SAW_BLADE_MOLD.get());
					output.accept(SurvivalReimaginedModItems.KNIFE_BLADE_MOLD.get());
					output.accept(SurvivalReimaginedModItems.WOODEN_PLATE.get());
					output.accept(SurvivalReimaginedModItems.CLAY_METAL_PLATE_MOLD.get());
					output.accept(SurvivalReimaginedModItems.METAL_PLATE_MOLD.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_PLATE.get());
					output.accept(SurvivalReimaginedModItems.STEEL_PLATE.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_PLATED_DIAMOND.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_NETHERITE.get());
					output.accept(SurvivalReimaginedModItems.TITANIUM_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_TITANIUM_ORE.get());
					output.accept(SurvivalReimaginedModItems.SHALE_TITANIUM_ORE.get());
					output.accept(SurvivalReimaginedModItems.RAW_TITANIUM.get());
					output.accept(SurvivalReimaginedModItems.RAW_TITANIUM_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_TITANIUM.get());
					output.accept(SurvivalReimaginedModItems.TITANIUM_INGOT.get());
					output.accept(SurvivalReimaginedModItems.BLOCK_OF_RAW_TITANIUM.get());
					output.accept(SurvivalReimaginedModItems.BLOCK_OF_TITANIUM.get());
					output.accept(SurvivalReimaginedModItems.URANINITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_URANINITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_URANINITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.SHALE_URANINITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.RAW_URANINITE.get());
					output.accept(SurvivalReimaginedModItems.URANIUM_DUST.get());
					output.accept(SurvivalReimaginedModItems.REDSTONE_CHARGED_URANIUM_DUST.get());
					output.accept(SurvivalReimaginedModItems.GOLD_ROD.get());
					output.accept(SurvivalReimaginedModItems.RAW_URANINITE_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_URANIUM.get());
					output.accept(SurvivalReimaginedModItems.URANIUM_INGOT.get());
					output.accept(SurvivalReimaginedModItems.BLOCK_OF_RAW_URANINITE.get());
					output.accept(SurvivalReimaginedModItems.BLOCK_OF_URANIUM.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_TURANITE.get());
					output.accept(SurvivalReimaginedModItems.TURANITE_INGOT.get());
					output.accept(SurvivalReimaginedModItems.TURANITE_BLOCK.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_PLATED_INGOT.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_PLATE.get());
					output.accept(SurvivalReimaginedModItems.NETHERITE_PLATE.get());
					output.accept(SurvivalReimaginedModItems.QUICK_LIME.get());
					output.accept(SurvivalReimaginedModItems.DARK_CINDER_POWDER.get());
					output.accept(SurvivalReimaginedModItems.DARK_CINDER_COAL.get());
					output.accept(SurvivalReimaginedModItems.SILVER_INGOT.get());
					output.accept(SurvivalReimaginedModItems.SILVER_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_SILVER_ORE.get());
					output.accept(SurvivalReimaginedModItems.ARGENTITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_ARGENTITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_ARGENTITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.RAW_SILVER.get());
					output.accept(SurvivalReimaginedModItems.RAW_SILVER_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_SILVER.get());
					output.accept(SurvivalReimaginedModItems.SILVER_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.ARGENTITE.get());
					output.accept(SurvivalReimaginedModItems.ARGENTITE_NUGGET.get());
					output.accept(SurvivalReimaginedModItems.RAW_SILVER_BLOCK.get());
					output.accept(SurvivalReimaginedModItems.SILVER_BLOCK.get());
					output.accept(SurvivalReimaginedModItems.ARGENTITE_BLOCK.get());
					output.accept(SurvivalReimaginedModItems.SAPPHIRE_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_SAPPHIRE_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_DIAMOND_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_EMERALD_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_LAPIS_ORE.get());
					output.accept(SurvivalReimaginedModItems.HEMATITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_HEMATITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.MAGNETITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_MAGNETITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.CALAVERITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_CALAVERITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.PYROLUSITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_PYROLUSITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.URANOPHANE_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_URANOPHANE_ORE.get());
					output.accept(SurvivalReimaginedModItems.ILMENITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_ILMENITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.ANTHRACITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_ANTHRACITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.LIGINITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_LIGINITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_HEMATITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_MAGNETITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_CALAVERITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_PYROLUSITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_URANOPHANE_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_ILMENITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_ANTHRACITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_LIGINITE_ORE.get());
					output.accept(SurvivalReimaginedModItems.KIMBERLITE.get());
					output.accept(SurvivalReimaginedModItems.KIMBERLITE_ROCK.get());
					output.accept(SurvivalReimaginedModItems.KIMBERLITE_SAPPHIRE_ORE.get());
					output.accept(SurvivalReimaginedModItems.KIMBERLITE_DIAMOND_ORE.get());
					output.accept(SurvivalReimaginedModItems.KIMBERLITE_EMERALD_ORE.get());
					output.accept(SurvivalReimaginedModItems.KIMBERLITE_RUBY_ORE.get());
					output.accept(SurvivalReimaginedModItems.KIMBERLITE_LAPIS_ORE.get());
					output.accept(SurvivalReimaginedModItems.KIMBERLITE_AMBER_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_SAPPHIRE_ORE.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_SAPPHIRE.get());
					output.accept(SurvivalReimaginedModItems.SAPPHIRE_BLOCK.get());
					output.accept(SurvivalReimaginedModItems.RUBY_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_RUBY_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_RUBY_ORE.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_RUBY.get());
					output.accept(SurvivalReimaginedModItems.BLOCK_OF_RUBY.get());
					output.accept(SurvivalReimaginedModItems.AMBER_ORE.get());
					output.accept(SurvivalReimaginedModItems.DEEPSLATE_AMBER_ORE.get());
					output.accept(SurvivalReimaginedModItems.BASALT_AMBER_ORE.get());
					output.accept(SurvivalReimaginedModItems.ROUGH_AMBER.get());
					output.accept(SurvivalReimaginedModItems.BLOCK_OF_AMBER.get());
					output.accept(SurvivalReimaginedModItems.WOODEN_RUNE.get());
					output.accept(SurvivalReimaginedModItems.RUNE_CLAY_MOLD.get());
					output.accept(SurvivalReimaginedModItems.RUNE_MOLD.get());
					output.accept(SurvivalReimaginedModItems.EMPTY_GOLD_RUNE.get());
					output.accept(SurvivalReimaginedModItems.EMPTY_SILVER_RUNE.get());
					output.accept(SurvivalReimaginedModItems.SAPPHIRE.get());
					output.accept(SurvivalReimaginedModItems.AMBER.get());
					output.accept(SurvivalReimaginedModItems.RUBY.get());
					output.accept(SurvivalReimaginedModItems.SAPPHIRE_SILVER_RUNE.get());
					output.accept(SurvivalReimaginedModItems.SAPPHIRE_GOLD_RUNE.get());
					output.accept(SurvivalReimaginedModItems.SILVER_AMBER_RUNE.get());
					output.accept(SurvivalReimaginedModItems.GOLD_AMBER_RUNE.get());
					output.accept(SurvivalReimaginedModItems.SILVER_DIAMOND_RUNE.get());
					output.accept(SurvivalReimaginedModItems.GOLD_DIAMOND_RUNE.get());
					output.accept(SurvivalReimaginedModItems.SILVER_EMERALD_RUNE.get());
					output.accept(SurvivalReimaginedModItems.GOLD_EMERALD_RUNE.get());
					output.accept(SurvivalReimaginedModItems.SILVER_RUBY_RUNE.get());
					output.accept(SurvivalReimaginedModItems.GOLD_RUBY_RUNE.get());
					output.accept(SurvivalReimaginedModItems.SILVER_LAPIS_RUNE.get());
					output.accept(SurvivalReimaginedModItems.GOLD_LAPIS_RUNE.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_SWORD_BLADE.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_PICKAXE_HEAD.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_AXE_HEAD.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_SHOVEL_HEAD.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_HOE_BLADE.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_HAMMER_HEAD.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_SAW_BLADE.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_KNIFE_BLADE.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_HAMMER.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_SAW.get());
					output.accept(SurvivalReimaginedModItems.DIAMOND_KNIFE.get());

					output.accept(SurvivalReimaginedModItems.BRONZE_SWORD_BLADE.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_PICKAXE_HEAD.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_AXE_HEAD.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_SHOVEL_HEAD.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_HOE_BLADE.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_HAMMER_HEAD.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_SAW_BLADE.get());
					output.accept(SurvivalReimaginedModItems.BRONZE_KNIFE_BLADE.get());

					output.accept(SurvivalReimaginedModItems.STEEL_SWORD_BLADE.get());
					output.accept(SurvivalReimaginedModItems.STEEL_PICKAXE_HEAD.get());
					output.accept(SurvivalReimaginedModItems.STEEL_AXE_HEAD.get());
					output.accept(SurvivalReimaginedModItems.STEEL_SHOVEL_HEAD.get());
					output.accept(SurvivalReimaginedModItems.STEEL_HOE_BLADE.get());
					output.accept(SurvivalReimaginedModItems.STEEL_HAMMER_HEAD.get());
					output.accept(SurvivalReimaginedModItems.STEEL_SAW_BLADE.get());
					output.accept(SurvivalReimaginedModItems.STEEL_KNIFE_BLADE.get());
					output.accept(SurvivalReimaginedModItems.STEEL_SWORD.get());
					output.accept(SurvivalReimaginedModItems.STEEL_PICKAXE.get());
					output.accept(SurvivalReimaginedModItems.STEEL_AXE.get());
					output.accept(SurvivalReimaginedModItems.STEEL_SHOVEL.get());
					output.accept(SurvivalReimaginedModItems.STEEL_HOE.get());
					output.accept(SurvivalReimaginedModItems.STEEL_HAMMER.get());
					output.accept(SurvivalReimaginedModItems.STEEL_SAW.get());
					output.accept(SurvivalReimaginedModItems.STEEL_KNIFE.get());
				})
				.build();
		Registry.register(BuiltInRegistries.CREATIVE_MODE_TAB, id, tab);
		return new RegistryEntry<>(id, tab);
	}

	public static void register() {
		// Forces class initialization.
	}
}
